// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOdBmVvI30Jg49oup4gsJMZMjTPhHOloQ',
    appId: '1:251418261584:web:2e01357a093d27476b7955',
    messagingSenderId: '251418261584',
    projectId: 'fullstack-labs',
    authDomain: 'fullstack-labs.firebaseapp.com',
    databaseURL: 'https://fullstack-labs.firebaseio.com',
    storageBucket: 'fullstack-labs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKCYPPpdpEuaTcg4hlK9s_oeD4spRZDUw',
    appId: '1:251418261584:android:69826f22d148c9436b7955',
    messagingSenderId: '251418261584',
    projectId: 'fullstack-labs',
    databaseURL: 'https://fullstack-labs.firebaseio.com',
    storageBucket: 'fullstack-labs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdIJ1dAm6ULKWDwLdd9eRfDXbUexUYHnY',
    appId: '1:251418261584:ios:17af11f293570e536b7955',
    messagingSenderId: '251418261584',
    projectId: 'fullstack-labs',
    databaseURL: 'https://fullstack-labs.firebaseio.com',
    storageBucket: 'fullstack-labs.appspot.com',
    iosClientId: '251418261584-117dqiomd0q2jogmjfeborr2nm90o120.apps.googleusercontent.com',
    iosBundleId: 'com.gdglawrence.flutterfestival',
  );
}
